EmpApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name="EmpApp"

urlpatterns = [
    path('',views.index,name='index'),
    path('accounts/login/',views.login_view,name='login'),
    path('accounts/logout/',views.logout_view,name='logout'),
    path('accounts/edit',views.edit,name='edit'),
    path('accounts/edit/step1',views.step,name='step'),
    path('accounts/edit/<str:msg>',views.edit_msg,name='edit_profile'),
    path('accounts/profile',views.profile,name='employee_profile')
]

EmpProject/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    # path('nested_admin/', include('nested_admin.urls')),
    path('',include('EmpApp.urls')),
    path('project/',include('project.urls')),
    path('admin/', admin.site.urls),
    path('employee/',include('employee.urls')),
    path('tasks/',include('tasks.urls')),
    path('manager/',include('manager.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name="manager"

urlpatterns = [
    path('dashboard',views.manager_dash,name = 'dashboard'),
    path('projects',views.my_projects,name = 'my_projects'),
    path('messages/admin/',views.admin_message,name='admin_msg'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name="project"

urlpatterns = [
    path('<str:slug>',views.indi_project,name='project_slug_detail'),
]

tasks/urls.py
from django.urls import path,include
from . import views



app_name="tasks"
urlpatterns = [

    path('add', views.addTask, name="addTask"),
    path('timesheet', views.timesheet, name="timesheet"),
    path('update', views.updateTask, name="updateTask"),

]

manager/models.py
from django.db import models

# Create your models here.

project/models.py
from django.db import models
from EmpApp.models import CustomUser, ManagerProfile, EmployeeProfile
from django.shortcuts import reverse
import os
from django.utils.text import slugify
import itertools



def project_requirement_directory(instance, filename):
    return 'projects/{0}/requirement_files/{1}'.format(instance.project.name, filename)

def project_documentation_directory(instance, filename):
    return 'projects/{0}/documentation_files/{1}'.format(instance.project.name, filename)

PROJECT_TYPE = (
    ('INTERNAL','Internal Project'),
    ('CLIENT','Client Project'),
)

class Project(models.Model):
    name = models.CharField(max_length=200)
    deadline = models.DateField()
    type = models.CharField(choices=PROJECT_TYPE, max_length=100)
    manager = models.ForeignKey(ManagerProfile, null=True, on_delete=models.SET_NULL)
    lead = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL)
    repository = models.URLField(max_length=200)
    slug = models.SlugField(max_length = 200)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug
        }
        # return "/project/%s" % self.slug
        return reverse('project:project_slug_detail', kwargs=kwargs)


    def _generate_slug(self):
        max_length = self._meta.get_field('slug').max_length
        value = self.name
        slug_candidate = slug_original = slugify(value, allow_unicode=True)
        for i in itertools.count(1):
            if not Project.objects.filter(slug=slug_candidate).exists():
                break
            slug_candidate = '{}-{}'.format(slug_original, i)

        self.slug = slug_candidate

    def save(self, *args, **kwargs):
        if not self.pk:
            self._generate_slug()

        super().save(*args, **kwargs)

class Team_member(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    member = models.ForeignKey(EmployeeProfile, null=True, on_delete=models.SET_NULL)


class Requirement(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    requirement_file = models.FileField(upload_to=project_requirement_directory)

    def filename(self):
        return os.path.basename(self.requirement_file.name)

class Documentation(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    file = models.FileField(upload_to=project_documentation_directory)

    def filename(self):
        return os.path.basename(self.file.name)


# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from EmpApp.models import EmployeeProfile, SessionLogs, ManagerProfile, AdminMessage
from EmpApp.decorators import is_manager
from project.models import Project

@is_manager(redirect_field_name="/")
def manager_dash(request):
    try:
        print(request.user)
        profile = EmployeeProfile.objects.get(user=request.user)
        print("profile", profile)
        if not profile.done:
            return redirect("EmpApp:edit")
    except:
        profile = False
    if not profile:
        return redirect("EmpApp:edit_profile", msg="newuser_redirect")

    mprofile = ManagerProfile.objects.get(employee=profile)
    my_projects = Project.objects.filter(manager=mprofile, completed=False)
    return render(request, 'manager/managerdash.html', {'projects':my_projects[:3]})


@is_manager(redirect_field_name="/")
def my_projects(request):
    pass






@is_manager(redirect_field_name="/")
def admin_message(request):
    messages = AdminMessage.objects.filter(to=request.user)
    context = {
        'messages':messages,
    }
    print(context)
    return render(request, 'manager/from_admin.html', context)

project/views.py
from django.shortcuts import render, get_object_or_404
from tasks.models import Task, Update
from .models import Project, Team_member, Requirement, Documentation
from EmpApp.models import EmployeeProfile
# Create your views here.
def indi_project(request, slug):
    project = get_object_or_404(Project, slug=slug)
    tms = Team_member.objects.filter(project=project)
    emps = EmployeeProfile.objects.all().exclude(role="MANAGER")
    tasks = Task.objects.filter(project=project)
    updates = Update.objects.filter(task__in=tasks)
    reqs = Requirement.objects.filter(project=project)
    docs = Documentation.objects.filter(project=project)
    projects = Project.objects.all()
    context = {
        'project':project,
        'tms':tms,
        'tasks':tasks,
        'reqs':reqs,
        'docs':docs,
        'updates':updates
    }
    if project.lead == request.user:
        return render(request, 'employee/project_lead.html', context)
    if request.user.is_manager:
        return render(request, 'manager/project.html', context)
    return render(request, 'employee/project.html', context)

templates/manager/Manager_Profile.html
{% extends 'manager/manager_base.html' %}

{% block content %}
{% load static %}
  <!-- Main content -->
  <div class="main-content" id="panel">
    <!-- Topnav -->
    <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Search form -->

          <!-- Navbar links -->
          <ul class="navbar-nav align-items-center  ml-md-auto ">
            <li class="nav-item d-xl-none">
              <!-- Sidenav toggler -->
              <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>vew
                  <i class="sidenav-toggler-line"></i>
                </div>
              </div>
            </li>
            <li class="nav-item d-sm-none">
              <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                <i class="ni ni-zoom-split-in"></i>
              </a>
            </li>
          </ul>
          <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
            <li class="nav-item dropdown">
              <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media align-items-center">
                  <span class="avatar avatar-sm rounded-circle">
                    <img alt="Image placeholder" src="{% static 'assets/img/theme/team-5.jpg' %}">
                  </span>
                  <div class="media-body  ml-2  d-none d-lg-block">
                    <span class="mb-0 text-sm  font-weight-bold">{{request.user.name}}</span>
                  </div>
                </div>
              </a>
              <div class="dropdown-menu  dropdown-menu-right ">
                <div class="dropdown-header noti-title">
                  <h6 class="text-overflow m-0">Welcome!</h6>
                </div>
                <a href="Employee_Profile.html" class="dropdown-item">
                  <i class="ni ni-single-02"></i>
                  <span>My profile</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-settings-gear-65"></i>
                  <span>Settings</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-calendar-grid-58"></i>
                  <span>Activity</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-support-16"></i>
                  <span>Support</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-user-run"></i>
                  <span>Logout</span>
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <br>
    <div class="container">
      <div class="row">
        <div class="col-sm-1 mt-1"></div>
        <div class="col-sm-5">

              <div class="media align-items-center">
                  <span class="rounded-circle">
                    <img alt="Image placeholder" class="rounded-circle" width="50%" height="50%" src="{% static 'assets/img/theme/team-5.jpg' %}">
                  </span>


                </div>
        </div>

        <div class="col-sm-6   ">
         <u> <h1 class="text-uppercase">Welcome !!</h1></u>
        <h2 class="text-capitalize my-auto">{{request.user.name}}</h2>
        <h2 class="">{{request.user.email}}</h2>
        <h2 class="">{{profile.role}}</h2>
          <h2 class="">Employee Id: {{request.user.employee_id}}</h2>

        </div>
      </div>
      <br>
      <center><b><h1 class="text-uppercase text-gray-dark"> Personal Details</h1></b></center><hr>
      <div class="row">
        <div class="col-sm-1 col-1"></div>
        <div class="col-sm-11 col-11">
          <a class="" href="/accounts/edit"><i class="fa fa-edit"></i></a>
        </div>
        <div class="col-sm-1 col-1"></div>
        <div class="col-sm-3 col-3 ">
           <h2 class=""> Name :</h2>
           <h2 class=""> Address :</h2>
           <h2 class=""> phone number:</h2>
           <h2 class=""> Position  :</h2>
           <h2 class=""> Department :</h2>
           <h2>Working Projects:</h2>
        </div>
        <div class="col-sm-8 col-8">
            <h2 class="">{{request.user.name}}</h2>
            <h2 class="">{{profile.address}}</h2>
            <h2>{{profile.phone_no}}</h2>
            <h2>{% if request.user.is_manager %} Manager {% else %} Employee {% endif %}</h2>
            <h2>{{profile.role}}</h2>
            <h2>Employee Management System, Smart Parking</h2>
        </div>
        <div class="container">
          <div class="container">
            <div class="mt-3">
              <div class="text-center">
                <h3>Skills</h3>
                <div class="m-auto">
                  <table class="table table-striped">
                    <thead class="table-dark">
                      <tr>
                        <th>Skill</th>
                        <th>Rating</th
                      </tr>
                    </thead>
                    {% for skill in skills %}
                      <tr>
                        <td>{{skill.skill}}</td>
                        <td>{{skill.rating}}</td>
                      </tr>
                    {% endfor %}
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> <hr>
       <br>
      </div>
      <div>

    </div>
      <!-- Footer -->
      <footer class="footer pt-0">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-lg-6">
            <div class="copyright text-center  text-lg-left  text-muted">
              &copy;   @ 2020 <a href="https://engagenreap.com" class="font-weight-bold ml-1" target="_blank">Enr Consultancy Services</a>
            </div>
          </div>
          <div class="col-lg-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
              <li class="nav-item">
                <a href="https://engagenreap.com/aboutus.html" class="nav-link" target="_blank">About Us</a>
              </li>


            </ul>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
</body>


{% endblock %}

templates/manager/from_admin.html
{% extends 'manager/manager_base.html' %}

{% block content %}
{% load static %}

  <!-- Main content -->
  <div class="main-content" id="panel">
    <!-- Topnav -->
    <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Search form -->
        <h1 class="display-3 text-white">Welcome John!!</h1>
          <!-- Navbar links -->
          <ul class="navbar-nav align-items-center  ml-md-auto ">
            <li class="nav-item d-xl-none">
              <!-- Sidenav toggler -->
              <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>vew
                  <i class="sidenav-toggler-line"></i>
                </div>
              </div>
            </li>
            <li class="nav-item d-sm-none">
              <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                <i class="ni ni-zoom-split-in"></i>
              </a>
            </li>
          </ul>
          <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
            <li class="nav-item dropdown">
              <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media align-items-center">
                  <span class="avatar avatar-sm rounded-circle">
                    <img alt="Image placeholder" src="{% static 'assets/img/theme/team-5.jpg' %}">
                  </span>
                  <div class="media-body  ml-2  d-none d-lg-block">
                    <span class="mb-0 text-sm  font-weight-bold">John Snow</span>
                  </div>
                </div>
              </a>
              <div class="dropdown-menu  dropdown-menu-right ">
                <div class="dropdown-header noti-title">
                  <h6 class="text-overflow m-0">Welcome!</h6>
                </div>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-single-02"></i>
                  <span>My profile</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-settings-gear-65"></i>
                  <span>Settings</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-calendar-grid-58"></i>
                  <span>Activity</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-support-16"></i>
                  <span>Support</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-user-run"></i>
                  <span>Logout</span>
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Header -->
    <!-- Header -->
    <div class="container">
      <div class="container">

        <center>
          <div class="container">
            <div class="bg-white card h-100 rounded" style="min-height:300px; border: .5px solid black;">
              {% for message in messages %}
              <div class="m-auto message">
                <h4>
                  {{message.message}}
                </h4>
              </div>
              {% endfor %}
            </div>
          </div>
        </center>

      </div>
      </div>
      <!-- Footer -->
      <footer class="footer pt-0">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-lg-6">
            <div class="copyright text-center  text-lg-left  text-muted">
              &copy;   @ 2020 <a href="https://engagenreap.com" class="font-weight-bold ml-1" target="_blank">Enr Consultancy Services</a>
            </div>
          </div>
          <div class="col-lg-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
              <li class="nav-item">
                <a href="https://engagenreap.com/aboutus.html" class="nav-link" target="_blank">About Us</a>
              </li>


            </ul>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
  {% endblock %}

templates/manager/manager_base.html
<!DOCTYPE html>
<html>


{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>Manager Page</title>
  <!-- Favicon -->
  <link rel="icon" href="{% static 'assets/img/brand/favicon.png' %}" type="image/png">
  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" type="text/css">
  <!-- Page plugins -->
  <!-- Argon CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/argon.css' %}" type="text/css">
  <script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
  <!-- Optional JS -->
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>
  <!-- Argon JS -->
  <script src="{% static 'assets/js/argon.js' %}"></script>
</head>

<body>
  <!-- Sidenav -->
  <nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
      <!-- Brand -->
      <div class="sidenav-header  align-items-center">
        <a class="navbar-brand" href="javascript:void(0)">
          <h1><img src="https://engagenreap.pythonanywhere.com/static/logo2.png" width="40">Manager Portal</h1>
        </a>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {% if 'dashboard' in request.path %} active {% endif %}" href="{% url 'manager:dashboard' %}">
                <i class="ni ni-tv-2 text-primary"></i>
                <span class="nav-link-text">Dashboard</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'profile' in request.path %} active {% endif %}{% if 'edit' in request.path %} active {% endif %}" href="{% url 'EmpApp:employee_profile' %}">
                <i class="ni ni-planet text-orange"></i>
                <span class="nav-link-text">My Profile</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'project' in request.path %} active {% endif %}" href="">
                <i class="ni ni-pin-3 text-primary"></i>
                <span class="nav-link-text">My Projects</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'meeting' in request.path %} active {% endif %}" href="Employee_Meeting.html">
                <i class="ni ni-single-02 text-yellow"></i>
                <span class="nav-link-text">Meeting scedules</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'admin' in request.path %} active {% endif %}" href="{% url 'manager:admin_msg' %}">
                  <i class="ni ni-bullet-list-67 text-default">
                    {% if count >= 1 %}
                      <span class="noti-sub">{{count}}</span>
                    {% endif %}
                  </i>
                <span class="nav-link-text">Messages From admin</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/accounts/logout">
                <i class="ni ni-user-run text-default"></i>
                <span class="nav-link-text">Logout</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

{% block content %}

{% endblock %}


</body>