EmpApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name="EmpApp"

urlpatterns = [
    path('',views.index,name='index'),
    path('accounts/login/',views.login_view,name='login'),
    path('accounts/logout/',views.logout_view,name='logout'),
    path('accounts/edit',views.edit,name='edit'),
    path('accounts/edit/step1',views.step,name='step'),
    path('accounts/edit/<str:msg>',views.edit_msg,name='edit_profile'),
    path('accounts/profile',views.profile,name='employee_profile')
]

EmpProject/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    # path('nested_admin/', include('nested_admin.urls')),
    path('',include('EmpApp.urls')),
    path('project/',include('project.urls')),
    path('admin/', admin.site.urls),
    path('employee/',include('employee.urls')),
    path('tasks/',include('tasks.urls')),
    path('manager/',include('manager.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

employee/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name="employee"

urlpatterns = [
    path('messages/admin/',views.admin_message,name='admin_msg'),
    path('dashboard',views.employee_dash,name = 'dashboard'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name="project"

urlpatterns = [
    path('<str:slug>',views.indi_project,name='project_slug_detail'),
]

tasks/urls.py
from django.urls import path,include
from . import views



app_name="tasks"
urlpatterns = [

    path('add', views.addTask, name="addTask"),
    path('timesheet', views.timesheet, name="timesheet"),
    path('update', views.updateTask, name="updateTask"),

]

employee/models.py
from django.db import models

# Create your models here.

project/models.py
from django.db import models
from EmpApp.models import CustomUser, ManagerProfile, EmployeeProfile
from django.shortcuts import reverse
import os
from django.utils.text import slugify
import itertools



def project_requirement_directory(instance, filename):
    return 'projects/{0}/requirement_files/{1}'.format(instance.project.name, filename)

def project_documentation_directory(instance, filename):
    return 'projects/{0}/documentation_files/{1}'.format(instance.project.name, filename)

PROJECT_TYPE = (
    ('INTERNAL','Internal Project'),
    ('CLIENT','Client Project'),
)

class Project(models.Model):
    name = models.CharField(max_length=200)
    deadline = models.DateField()
    type = models.CharField(choices=PROJECT_TYPE, max_length=100)
    manager = models.ForeignKey(ManagerProfile, null=True, on_delete=models.SET_NULL)
    lead = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL)
    repository = models.URLField(max_length=200)
    slug = models.SlugField(max_length = 200)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug
        }
        # return "/project/%s" % self.slug
        return reverse('project:project_slug_detail', kwargs=kwargs)


    def _generate_slug(self):
        max_length = self._meta.get_field('slug').max_length
        value = self.name
        slug_candidate = slug_original = slugify(value, allow_unicode=True)
        for i in itertools.count(1):
            if not Project.objects.filter(slug=slug_candidate).exists():
                break
            slug_candidate = '{}-{}'.format(slug_original, i)

        self.slug = slug_candidate

    def save(self, *args, **kwargs):
        if not self.pk:
            self._generate_slug()

        super().save(*args, **kwargs)

class Team_member(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    member = models.ForeignKey(EmployeeProfile, null=True, on_delete=models.SET_NULL)


class Requirement(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    requirement_file = models.FileField(upload_to=project_requirement_directory)

    def filename(self):
        return os.path.basename(self.requirement_file.name)

class Documentation(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    file = models.FileField(upload_to=project_documentation_directory)

    def filename(self):
        return os.path.basename(self.file.name)


# Create your models here.

employee/views.py
from django.shortcuts import render, redirect
from EmpApp.models import EmployeeProfile, SessionLogs, AdminMessage
import datetime
from project.models import Project, Team_member
from tasks.models import Task

def employee_dash(request):
    try:
        profile = EmployeeProfile.objects.get(user=request.user)
        if not profile.done:
            return redirect("EmpApp:edit")
    except:
        profile = False
    if not profile:
        return redirect("EmpApp:edit_profile", msg="newuser_redirect")

    enddate = datetime.date.today() + datetime.timedelta(days=1)
    startdate = enddate - datetime.timedelta(days=6)
    sessions = SessionLogs.objects.filter(user=request.user, login_time__range=[startdate, enddate]).order_by('login_time')
    time_logged_in = []
    print(sessions)
    # first = sessions[:1].login_time.date()
    # print(first)
    seconds = 0
    day_hour = []
    dicts_lis = []
    try:
        k = sessions[0].login_time.strftime("%d/%m/%Y")
    except:
        pass
    for session in sessions:
        if k == session.login_time.strftime("%d/%m/%Y"):
            try:
                z = session.logout_time-session.login_time
                seconds+= z.total_seconds()
                print(seconds, z)
            except:
                day_hour.append([k, seconds/3600])
                dicts_lis.append({'label':k, 'y':seconds/3600})
                k = session.login_time.strftime("%d/%m/%Y")
                seconds = 0
            continue
        day_hour.append([k, seconds/3600])
        dicts_lis.append({'label':k, 'y':seconds/3600})
        k = session.login_time.strftime("%d/%m/%Y")
        seconds = 0
    involved_in = Team_member.objects.filter(member=profile)
    my_projects = []
    for i in involved_in:
        mp = []
        project = Project.objects.get(id=i.project.id)
        mp.append(project)
        mp.append(Task.objects.filter(employee=request.user, project=project))
        my_projects.append(mp)
    print(day_hour)


    return render(request, 'employee/employeedash.html', {'sessions':day_hour[::-1], 'session2':dicts_lis, 'projects': my_projects})



def admin_message(request):
    if request.user.is_authenticated:
        messages = AdminMessage.objects.filter(to=request.user)
        context = {
            'messages':messages,
        }
        print(context)
        for i in messages:
            i.seen = True
            i.save()
        return render(request, 'employee/from_admin.html', context)

project/views.py
from django.shortcuts import render, get_object_or_404
from tasks.models import Task, Update
from .models import Project, Team_member, Requirement, Documentation
from EmpApp.models import EmployeeProfile
# Create your views here.
def indi_project(request, slug):
    project = get_object_or_404(Project, slug=slug)
    tms = Team_member.objects.filter(project=project)
    emps = EmployeeProfile.objects.all().exclude(role="MANAGER")
    tasks = Task.objects.filter(project=project)
    updates = Update.objects.filter(task__in=tasks)
    reqs = Requirement.objects.filter(project=project)
    docs = Documentation.objects.filter(project=project)
    projects = Project.objects.all()
    context = {
        'project':project,
        'tms':tms,
        'tasks':tasks,
        'reqs':reqs,
        'docs':docs,
        'updates':updates
    }
    if project.lead == request.user:
        return render(request, 'employee/project_lead.html', context)
    if request.user.is_manager:
        return render(request, 'manager/project.html', context)
    return render(request, 'employee/project.html', context)

templates/employee/Employee_Profile.html
{% extends 'employee/employee_base.html' %}

{% block content %}
{% load static %}
  <!-- Main content -->
  <div class="main-content" id="panel">
    <!-- Topnav -->
    <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Search form -->

          <!-- Navbar links -->
          <ul class="navbar-nav align-items-center  ml-md-auto ">
            <li class="nav-item d-xl-none">
              <!-- Sidenav toggler -->
              <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>vew
                  <i class="sidenav-toggler-line"></i>
                </div>
              </div>
            </li>
            <li class="nav-item d-sm-none">
              <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                <i class="ni ni-zoom-split-in"></i>
              </a>
            </li>
          </ul>
          <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
            <li class="nav-item dropdown">
              <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media align-items-center">
                  <span class="avatar avatar-sm rounded-circle">
                    <img alt="Image placeholder" src="{% static 'assets/img/theme/team-5.jpg' %}">
                  </span>
                  <div class="media-body  ml-2  d-none d-lg-block">
                    <span class="mb-0 text-sm  font-weight-bold">{{request.user.name}}</span>
                  </div>
                </div>
              </a>
              <div class="dropdown-menu  dropdown-menu-right ">
                <div class="dropdown-header noti-title">
                  <h6 class="text-overflow m-0">Welcome!</h6>
                </div>
                <a href="Employee_Profile.html" class="dropdown-item">
                  <i class="ni ni-single-02"></i>
                  <span>My profile</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-settings-gear-65"></i>
                  <span>Settings</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-calendar-grid-58"></i>
                  <span>Activity</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-support-16"></i>
                  <span>Support</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-user-run"></i>
                  <span>Logout</span>
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <br>
    <div class="container">
      <div class="row">
        <div class="col-sm-1 mt-1"></div>
        <div class="col-sm-5">

              <div class="media align-items-center">
                  <span class="rounded-circle">
                    <img alt="Image placeholder" class="rounded-circle" width="50%" height="50%" src="{% static 'assets/img/theme/team-5.jpg' %}">
                  </span>


                </div>
        </div>

        <div class="col-sm-6   ">
         <u> <h1 class="text-uppercase">Welcome !!</h1></u>
        <h2 class="text-capitalize my-auto">{{request.user.name}}</h2>
        <h2 class="">{{request.user.email}}</h2>
        <h2 class="">{{profile.role}}</h2>
          <h2 class="">Employee Id: {{request.user.employee_id}}</h2>

        </div>
      </div>
      <br>
      <center><b><h1 class="text-uppercase text-gray-dark"> Personal Details</h1></b></center><hr>
      <div class="row">
        <div class="col-sm-1 col-1"></div>
        <div class="col-sm-11 col-11">
          <a class="" href="/accounts/edit"><i class="fa fa-edit"></i></a>
        </div>
        <div class="col-sm-1 col-1"></div>
        <div class="col-sm-3 col-3 ">
           <h2 class=""> Name :</h2>
           <h2 class=""> Address :</h2>
           <h2 class=""> phone number:</h2>
           <h2 class=""> Position  :</h2>
           <h2 class=""> Department :</h2>
           <h2>Working Projects:</h2>
        </div>
        <div class="col-sm-8 col-8">
            <h2 class="">{{request.user.name}}</h2>
            <h2 class="">{{profile.address}}</h2>
            <h2>{{profile.phone_no}}</h2>
            <h2>{% if request.user.is_manager %} Manager {% else %} Employee {% endif %}</h2>
            <h2>{{profile.role}}</h2>
            <h2>Employee Management System, Smart Parking</h2>
        </div>
        <div class="container">
          <div class="container">
            <div class="mt-3">
              <div class="text-center">
                <h3>Skills</h3>
                <div class="m-auto">
                  <table class="table table-striped">
                    <thead class="table-dark">
                      <tr>
                        <th>Skill</th>
                        <th>Rating</th
                      </tr>
                    </thead>
                    {% for skill in skills %}
                      <tr>
                        <td>{{skill.skill}}</td>
                        <td>{{skill.rating}}</td>
                      </tr>
                    {% endfor %}
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> <hr>
       <br>
      </div>
      <div>

    </div>
      <!-- Footer -->
      <footer class="footer pt-0">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-lg-6">
            <div class="copyright text-center  text-lg-left  text-muted">
              &copy;   @ 2020 <a href="https://engagenreap.com" class="font-weight-bold ml-1" target="_blank">Enr Consultancy Services</a>
            </div>
          </div>
          <div class="col-lg-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
              <li class="nav-item">
                <a href="https://engagenreap.com/aboutus.html" class="nav-link" target="_blank">About Us</a>
              </li>


            </ul>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
</body>


{% endblock %}

templates/employee/dash_card.html
<div class="form-check projects">
 <div class="row"  id="headingOne">
   <div class="col-sm-8">
     <h3 class="m-auto"><a href={{project.0.get_absolute_url}}>{{project.0.name}}</a></h3>
   </div>
   <div class="col-sm-3" data-toggle="collapse" data-target="#{{project.0.slug}}" aria-expanded="true" aria-controls="{{project.0.slug}}">
     <h5 class="m-auto"><b>Deadline:</b> {{project.0.deadline}}</h5>
   </div>
   <div class="col-sm-1" data-toggle="collapse" data-target="#{{project.0.slug}}" aria-expanded="true" aria-controls="{{project.0.slug}}">
     <div class="m-auto"><i class="fa fa-caret-down"></i></div>
   </div>
 </div>
 <div class="row mt-3">
   <div id="{{project.0.slug}}" class="collapse w-100" aria-labelledby="headingOne" data-parent="body">
     <!-- {% for task in project.1 %}
        <ul class="w-100">
          <li class="w-100">
            <div class="row">
              <div class="col-sm-10">
                {{task.task_detail}}
              </div>
              <div class="col-sm-2">
                {{task.completed}}
              </div>
            </div>
          </li>
        </ul> -->
        <table class="table">
          <thead>
            <th>S.No.</th>
            <th>Task</th>
            <th>By</th>
            <th>Completed</th>
          </thead>
          <tbody>
            {% for task in project.1 %}
            <tr>
              <td>
                {{forloop.counter}}
              </td>
              <td>
                {{task.task_detail}}
              </td>
              <td>
                {{task.by_des}}
              </td>
              <td>
                {% if task.completed %}
                  <i class="fa fa-check green"></i>
                {% else %}
                  <i class="fa fa-times red"></i>
                {% endif %}
              </td>
            </tr>
            {% endfor %}

          </tbody>
        </table>
     <!-- {% endfor %} -->
   </div>
</div>
</div>

templates/employee/dash_card_lead.html
<a href={{project.0.get_absolute_url}} class="form-check projects">
   <div class="row">
     <div class="col-sm-8">
       <h3 class="m-auto">{{project.0.name}} (You Are Leading)</h3>
     </div>
     <div class="col-sm-3">
       <h5 class="m-auto"><b>Deadline:</b> {{project.0.deadline}}</h5>
     </div>
     <div class="col-sm-1">
       <h3 class="m-auto"><i class="fa fa-arrow-right"></i></h3>
     </div>
   </div>
</a>

templates/employee/employee_base.html
<!DOCTYPE html>
<html>


{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>Employee Page</title>
  <!-- Favicon -->
  <link rel="icon" href="{% static 'assets/img/brand/favicon.png' %}" type="image/png">
  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" type="text/css">
  <!-- Page plugins -->
  <!-- Argon CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/argon.css' %}" type="text/css">
  <script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
  <!-- Optional JS -->
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>
  <!-- Argon JS -->
  <script src="{% static 'assets/js/argon.js' %}"></script>
</head>

<body>
  <!-- Sidenav -->
  <nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
      <!-- Brand -->
      <div class="sidenav-header  align-items-center">
        <a class="navbar-brand" href="javascript:void(0)">
          <h1><img src="https://engagenreap.pythonanywhere.com/static/logo2.png" width="40">Employee Portal</h1>
        </a>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {% if 'dashboard' in request.path %} active {% endif %}" href="{% url 'employee:dashboard' %}">
                <i class="ni ni-tv-2 text-primary"></i>
                <span class="nav-link-text">Dashboard</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'profile' in request.path %} active {% endif %}{% if 'edit' in request.path %} active {% endif %}" href="{% url 'EmpApp:employee_profile' %}">
                <i class="ni ni-planet text-orange"></i>
                <span class="nav-link-text">My Profile</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'project' in request.path %} active {% endif %}" href="">
                <i class="ni ni-pin-3 text-primary"></i>
                <span class="nav-link-text">My Projects</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'meeting' in request.path %} active {% endif %}" href="Employee_Meeting.html">
                <i class="ni ni-single-02 text-yellow"></i>
                <span class="nav-link-text">Meeting scedules</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'admin' in request.path %} active {% endif %}" href="{% url 'employee:admin_msg' %}">
                <i class="ni ni-bullet-list-67 text-default">
                  {% if count >= 1 %}
                    <span class="noti-sub">{{count}}</span>
                  {% endif %}
                </i>
                <span class="nav-link-text">Messages From admin</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                <i class="ni ni-user-run text-default"></i>
                <span class="nav-link-text">Logout</span>
              </a>

              <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Today's Works</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js" integrity="sha512-ltwjKsDTo3hW/wV66ZaEkf2wOAFxmg7rWM76J8kOcYKLSKy44WBYO/BFaNNH3NGDS8BSz3meB9wtSnm41oL+pA==" crossorigin="anonymous"></script>

                    <form class="" action="{% url 'tasks:timesheet' %}" method="post">
                      <div class="modal-body">
                        <table class="table">
                          {% csrf_token %}
                          {{time_sheet_formset}}
                        </table>
                      </div>
                      <script type="text/javascript">
                      function add_remove(type){
                        $(`.${type} .table`).formset({
                          addText: `<div class="btn mb-2 btn-primary"><i class="fa fa-plus"></i> Add More</div>`,
                          prefix: '{{ time_sheet_formset.prefix }}',
                          deleteText: `<div class="btn mt-2 btn-warning"><i class="fa fa-times"></i> Remove</div>`
                        });
                      }
                      add_remove("modal-body");
                      </script>
                      <div class="modal-footer">
                        <button type="submit" name="button" class="btn btn-primary">Submit & Logout</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

{% block content %}

{% endblock %}


</body>

templates/employee/from_admin.html
{% extends 'employee/employee_base.html' %}

{% block content %}
{% load static %}

  <!-- Main content -->
  <div class="main-content" id="panel">
    <!-- Topnav -->
    <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Search form -->
        <h1 class="display-3 text-white">Welcome John!!</h1>
          <!-- Navbar links -->
          <ul class="navbar-nav align-items-center  ml-md-auto ">
            <li class="nav-item d-xl-none">
              <!-- Sidenav toggler -->
              <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>vew
                  <i class="sidenav-toggler-line"></i>
                </div>
              </div>
            </li>
            <li class="nav-item d-sm-none">
              <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                <i class="ni ni-zoom-split-in"></i>
              </a>
            </li>
          </ul>
          <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
            <li class="nav-item dropdown">
              <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media align-items-center">
                  <span class="avatar avatar-sm rounded-circle">
                    <img alt="Image placeholder" src="{% static 'assets/img/theme/team-5.jpg' %}">
                  </span>
                  <div class="media-body  ml-2  d-none d-lg-block">
                    <span class="mb-0 text-sm  font-weight-bold">John Snow</span>
                  </div>
                </div>
              </a>
              <div class="dropdown-menu  dropdown-menu-right ">
                <div class="dropdown-header noti-title">
                  <h6 class="text-overflow m-0">Welcome!</h6>
                </div>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-single-02"></i>
                  <span>My profile</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-settings-gear-65"></i>
                  <span>Settings</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-calendar-grid-58"></i>
                  <span>Activity</span>
                </a>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-support-16"></i>
                  <span>Support</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-user-run"></i>
                  <span>Logout</span>
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Header -->
    <!-- Header -->
    <div class="container">
  <center><h1>Messages From Admin</h1></center>
</div>
<br>
<div class="container">

  <center>
    <div class="container">
      <div class="bg-white card h-100 rounded" style="min-height:300px; border: .5px solid black;">
        {% for message in messages %}
        <div class="m-auto message">
          <h4>
            {{message.message}}
          </h4>
        </div>
        {% endfor %}
      </div>
    </div>
  </center>

</div>

      <!-- Footer -->
      <footer class="footer pt-0">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-lg-6">
            <div class="copyright text-center  text-lg-left  text-muted">
              &copy;   @ 2020 <a href="https://engagenreap.com" class="font-weight-bold ml-1" target="_blank">Enr Consultancy Services</a>
            </div>
          </div>
          <div class="col-lg-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
              <li class="nav-item">
                <a href="https://engagenreap.com/aboutus.html" class="nav-link" target="_blank">About Us</a>
              </li>


            </ul>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
  {% endblock %}